# Generated by Django 6.0.3 on 2026-04-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('market_price', models.FloatField()),
                ('promo_market_price', models.FloatField(default=0)),
                ('product_type', models.CharField(choices=[('V', 'Variation'), ('S', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
