# Generated by Django 6.0.3 on 2026-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='market_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_market_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
